### ISSUE TITLE
Borked Schema Processing

### ISSUE THREAD

**Issue by adam-codeberg** [brandicted/ramses-example#47]
/schemas/profile.json LN 44

``` json
        "user": {
            "type": ["string", "null"]
        }
```

type is loaded into a list[] and does not play well with /ramses/models.py LN 137

``` python
        raml_type = (props.get('type', 'string') or 'string').lower()
        if raml_type not in type_fields:
            raise ValueError('Unknown type: {}'.format(raml_type))
```

Results in list.lower() which wont work as there is no lower() method for lists.

Not sure if this was a bug or due to the examples being out dated with the current ramses release.

**Comment by postatum** [comment]
Hi @adam-codeberg. Thanks for the feedback!

Did you encounter this not working while running ramses app or did you suggest this behaviour will happen by looking at the code?

Because ramses ignores fields that don't define `_db_settings` schema param. And field type is specified in `_db_settings.type`.

**Comment by adam-codeberg** [comment]
Hey there, 
Quick heads up. This issue has since been resolved with the current ramses version.

**Comment by postatum** [comment]
Good. Thanks for heads up @adam-codeberg.
